name: Sync to IGT Web App

on:
  push:
    branches:
      - prod
      - qa
      - ref
      - uat
  workflow_dispatch:

jobs:
  sync-to-igt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Clone target repository
        run: |
          # Clone target repo outside the source directory to avoid syncing it
          cd ..
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/kithmih/igt-web-app.git target-repo
          cd $GITHUB_WORKSPACE

      - name: Determine target branch
        id: branch
        run: |
          SOURCE_BRANCH=${GITHUB_REF#refs/heads/}
          echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
          echo "Syncing from branch: $SOURCE_BRANCH"

      - name: Sync files to target repository
        run: |
          cd ../target-repo
          
          # Checkout or create the target branch
          SOURCE_BRANCH="${{ steps.branch.outputs.source_branch }}"
          git checkout $SOURCE_BRANCH || git checkout -b $SOURCE_BRANCH
          
          # Go back to sync files
          cd $GITHUB_WORKSPACE
          
          # Sync files excluding .github/ directory and other unwanted files
          rsync -av \
            --exclude='.github/' \
            --exclude='.git/' \
            --delete \
            ./ ../target-repo/

      - name: Commit and push changes
        run: |
          cd ../target-repo
          
          # Set git config to preserve original author info
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.event.head_commit.author.email }}"
          
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            
            # Use the original commit message if available, otherwise use a default
            COMMIT_MSG="${{ github.event.head_commit.message }}"
            if [ -z "$COMMIT_MSG" ]; then
              COMMIT_MSG="Sync from ig-web repo - Branch: ${{ steps.branch.outputs.source_branch }}"
            fi
            
            git commit -m "$COMMIT_MSG"
            git push origin ${{ steps.branch.outputs.source_branch }}
            echo "Changes pushed successfully"
          else
            echo "No changes to commit"
          fi